# Generated by Django 4.0.5 on 2022-07-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='party',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='party',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
