# Generated by Django 4.0.5 on 2022-07-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_receipts_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.receipts'),
            preserve_default=False,
        ),
    ]
