# Generated by Django 4.0.5 on 2022-07-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_items_receipt_remove_itemtoperson_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipts',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.group'),
            preserve_default=False,
        ),
    ]
