# Generated by Django 4.0.5 on 2022-07-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_person_group_receipts_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.receipts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtoperson',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.person'),
            preserve_default=False,
        ),
    ]
