# Generated by Django 4.0.5 on 2022-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_receipts_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='groupName',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
